# --pv-recycler-pod-template-filepath-hostpath parameter
# rainy day scenario: a volume does not exist
apiVersion: v1
kind: Pod
metadata:
  name: hello-world
spec:
  restartPolicy: Never
  containers:
  - name: hello
    image: "ubuntu:14.04"
    command: ["/bin/echo", "hello", "world"]
