# Storage Class that does not contain any zone limitations setup by admin
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: sloz
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  zone: us-central1-a

