kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: task-pv-claim
  finalizers: [kubernetes.io/pvc-protection]
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
