kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: run-hostpath-provisioner
subjects:
  - kind: ServiceAccount
    name: hostpath-provisioner
    namespace: default
roleRef:
  kind: ClusterRole
  name: hostpath-provisioner-runner
  apiGroup: rbac.authorization.k8s.io
